@doc raw"""
    Lorentz{T<:Real}

A proper orthochronous Lorentz transformation, an element of Spin⁺(3,1) — the double cover
of the restricted Lorentz group SO⁺(3,1).

We work in the spacetime algebra ``Cl(3,1)`` with metric signature ``{−}{+}{+}{+}`` and
basis vectors `𝐭, 𝐱, 𝐲, 𝐳` satisfying `𝐭² = −1`, `𝐱² = 𝐲² = 𝐳² = +1`, all mutually
anticommuting.  The pseudoscalar ``𝐈 = 𝐭𝐱𝐲𝐳``` satisfies ``𝐈² = −𝟏``.

Elements of ``𝐑 ∈ \mathrm{Spin}⁺(3,1)`` live in the even subalgebra (grades 0, 2, 4) and
satisfy ``𝐑 𝐑̃ = 𝟏``, where ``𝐑̃`` is the GA reverse.  In particular, note that that
product *could* include a term proportional to the pseudoscalar; it is zero: ``𝐑 𝐑̃ = 𝟏 +
0 𝐈``.  This subalgebra splits into two parts:

- **Rotation subgroup**: generated by the spatial bivectors `𝐲𝐳`, `𝐱𝐳`, `𝐱𝐲`.
- **Boost sector**: generated by the timelike bivectors `𝐭𝐱`, `𝐭𝐲`, `𝐭𝐳`.

All elements of this algebra commute with the pseudoscalar ``𝐈``, which acts as the complex
unit for this subalgebra.  Note that ``𝒾𝐢 = 𝐭𝐱``, ``𝒾𝐣 = 𝐭𝐲``, ``𝒾𝐤 = 𝐭𝐳``,
relating spatial-rotation generators to boost generators (all with positive signs).
A boost along ``\hat{𝐧} = n^x\,𝐢 + n^y\,𝐣 + n^z\,𝐤`` (a unit `QuatVec`) with
rapidity ``η`` is thus

```math
𝐑 = \cosh(η/2)·𝟏 + \sinh(η/2)·(nˣ 𝐭𝐱 + nʸ 𝐭𝐲 + nᶻ 𝐭𝐳)
```

The two elements ``±R ∈ \mathrm{Spin}⁺(3,1)`` represent the same Lorentz transformation.
The real GA components and their encoding are described in [`ga_components`](@ref); as
usual, you can get the plain (complex) coefficients with [`components`](@ref).

## Operations

Compose with `*`, invert with `inv`, obtain the identity with `one`.
Apply to a Minkowski 4-vector `v = [vᵗ, vˣ, vʸ, vᶻ]` by calling `Λ(v)`.
Access the GA components via [`ga_components`](@ref).

## Constructors

Use the named constructor [`Boost`](@ref).  For a pure rotation, wrap a `Rotor{T}` as
`Lorentz{T}(complex.(components(R)...))` or simply compose boosts.
"""
const Lorentz{T<:Real} = Rotor{Complex{T}}

@doc raw"""
    ga_components(Λ::Lorentz{T}) → SVector{8, T}

Return the eight real geometric-algebra components of `Λ` in Cl(3,1), ordered
as in the even-subalgebra expansion of a Spin⁺(3,1) rotor:

```math
𝐑 = R^1 + R^𝐢\,𝐢 + R^𝐣\,𝐣 + R^𝐤\,𝐤 + R^{𝐭𝐱}\,𝐭𝐱 + R^{𝐭𝐲}\,𝐭𝐲 + R^{𝐭𝐳}\,𝐭𝐳 + R^𝐈\,𝐈
```

where ``𝐈 = 𝐭𝐱𝐲𝐳`` is the pseudoscalar of ``\mathrm{Cl}(3,1)``.

## Storage mapping

`Lorentz{T}` stores a unit quaternion ``𝐑 = w𝟏 + x𝐢 + y𝐣 + z𝐤`` with complex
coefficients ``w, x, y, z ∈ ℂ``, where the quaternionic basis elements `𝐢, 𝐣, 𝐤`
correspond to spatial bivectors according to
```math
\begin{gather}
𝐢 = 𝐳𝐲 = -𝐲𝐳, \\
𝐣 = 𝐱𝐳 = -𝐳𝐱, \\
𝐤 = 𝐲𝐱 = -𝐱𝐲,
\end{gather}
```
and the complex unit ``𝒾 ∈ ℂ`` maps to the pseudoscalar ``𝐈 = 𝐭𝐱𝐲𝐳``, so that
```math
\begin{gather}
𝒾𝐢 = 𝐭𝐱𝐲𝐳𝐳𝐲 = 𝐭𝐱, \\
𝒾𝐣 = 𝐭𝐱𝐲𝐳𝐱𝐳 = 𝐭𝐲, \\
𝒾𝐤 = 𝐭𝐱𝐲𝐳𝐲𝐱 = 𝐭𝐳,
\end{gather}
```

The eight real GA components read off from `w, x, y, z` as:

| GA component | quaternion expression | Cl(3,1) basis |
| :----------- | :-------------------- | :------------ |
| `R¹`         | ``\Re(w)``            | ``𝟏``         |
| `Rᶻʸ`        | ``\Re(x)``            | ``𝐳𝐲 = 𝐢``    |
| `Rˣᶻ`        | ``\Re(y)``            | ``𝐱𝐳 = 𝐣``    |
| `Rʸˣ`        | ``\Re(z)``            | ``𝐲𝐱 = 𝐤``    |
| `Rᵗˣ`        | ``\Im(x)``            | ``𝐭𝐱``        |
| `Rᵗʸ`        | ``\Im(y)``            | ``𝐭𝐲``        |
| `Rᵗᶻ`        | ``\Im(z)``            | ``𝐭𝐳``        |
| `Rᵗˣʸᶻ`      | ``\Im(w)``            | ``𝐭𝐱𝐲𝐳``      |

The unit-norm condition ``𝐑𝐑̃ = 𝟏`` — i.e., ``w² + x² + y² + z² = 1`` with complex
arithmetic — translates to two real conditions on the GA components:

```math
\begin{gather}
(R¹)² + (Rᶻʸ)² + (Rˣᶻ)² + (Rʸˣ)² - (Rᵗˣ)² - (Rᵗʸ)² - (Rᵗᶻ)² - (Rᵗˣʸᶻ)² = 1, \\
R¹ Rᵗˣʸᶻ + Rᶻʸ Rᵗˣ + Rˣᶻ Rᵗʸ + Rʸˣ Rᵗᶻ = 0.
\end{gather}
```
"""
function ga_components(Λ::Lorentz{T}) where {T<:Real}
    w, x, y, z = getfield(Λ, :components)
    @SVector [real(w), real(x), real(y), real(z), imag(x), imag(y), imag(z), imag(w)]
end

# ---------------------------------------------------------------------------
# Named constructors
# ---------------------------------------------------------------------------
"""
    Boost(η::T, n̂::AbstractVector) → Lorentz{T}
    Boost(η::T, n̂::QuatVec) → Lorentz{T}

Construct the pure boost with rapidity `η` along the unit direction `n̂`.

The second argument may be either a 3-element `AbstractVector` `[nˣ, nʸ, nᶻ]` or a
`QuatVec` (whose `x`, `y`, `z` components are used as the direction).

In the even subalgebra of Cl(3,1) the rotor is

```math
𝐑 = \\cosh(η/2)·𝟏 + \\sinh(η/2)·(nˣ\\,𝐭𝐱 + nʸ\\,𝐭𝐲 + nᶻ\\,𝐭𝐳).
```

See [`ga_components(::Lorentz)`](@ref) for the correspondence between
this GA form and the quaternion storage.
"""
function Boost(η::T, n̂::AbstractVector) where {T<:Real}
    length(n̂) == 3 || throw(DimensionMismatch("boost direction must be a 3-vector; got length $(length(n̂))"))
    ch, sh = cosh(η / 2), sinh(η / 2)
    return Rotor{Complex{T}}(
        complex(ch),
        complex(zero(T), sh * T(n̂[1])),
        complex(zero(T), sh * T(n̂[2])),
        complex(zero(T), sh * T(n̂[3])),
    )
end

function Boost(η::T, n̂::QuatVec) where {T<:Real}
    ch, sh = cosh(η / 2), sinh(η / 2)
    _, nx, ny, nz = components(n̂)
    return Rotor{Complex{T}}(
        complex(ch),
        complex(zero(T), sh * T(nx)),
        complex(zero(T), sh * T(ny)),
        complex(zero(T), sh * T(nz)),
    )
end

# ---------------------------------------------------------------------------
# Action on Minkowski 4-vectors
# ---------------------------------------------------------------------------

"""
    (Λ::Lorentz{T})(v::AbstractVector) → similar(v, T)

Apply `Λ` to the Minkowski 4-vector `v = [vᵗ, vˣ, vʸ, vᶻ]` (signature −+++)
and return the transformed vector in a fresh container of the same type with
element type `T`.

The action is the Spin⁺(3,1) sandwich `V′ = R·V·R̃` in Cl(3,1), where `R̃` is
the GA reverse.  The eight real GA components `(R¹, Rᶻʸ, …, Rᵗˣʸᶻ)` are
extracted via [`ga_components(::Lorentz)`](@ref), and the bilinear
expansion of the grade-1 projection of `R·V·R̃` is applied directly.
"""
function (Λ::Lorentz{T})(v::AbstractVector) where {T<:Real}
    R¹, Rᶻʸ, Rˣᶻ, Rʸˣ, Rᵗˣ, Rᵗʸ, Rᵗᶻ, Rᵗˣʸᶻ = ga_components(Λ)
    vᵗ = T(v[1])
    vˣ = T(v[2])
    vʸ = T(v[3])
    vᶻ = T(v[4])

    v′ᵗ =
        vᵗ * (R¹^2 + Rᵗˣ^2 + Rᵗˣʸᶻ^2 + Rᵗʸ^2 + Rᵗᶻ^2 + Rʸˣ^2 + Rˣᶻ^2 + Rᶻʸ^2) +
        vˣ * (2R¹ * Rᵗˣ - 2Rᵗˣʸᶻ * Rᶻʸ + 2Rᵗʸ * Rʸˣ - 2Rᵗᶻ * Rˣᶻ) +
        vʸ * (2R¹ * Rᵗʸ - 2Rᵗˣ * Rʸˣ - 2Rᵗˣʸᶻ * Rˣᶻ + 2Rᵗᶻ * Rᶻʸ) +
        vᶻ * (2R¹ * Rᵗᶻ + 2Rᵗˣ * Rˣᶻ - 2Rᵗˣʸᶻ * Rʸˣ - 2Rᵗʸ * Rᶻʸ)

    v′ˣ =
        vᵗ * (2R¹ * Rᵗˣ - 2Rᵗˣʸᶻ * Rᶻʸ - 2Rᵗʸ * Rʸˣ + 2Rᵗᶻ * Rˣᶻ) +
        vˣ * (R¹^2 + Rᵗˣ^2 + Rᵗˣʸᶻ^2 - Rᵗʸ^2 - Rᵗᶻ^2 - Rʸˣ^2 - Rˣᶻ^2 + Rᶻʸ^2) +
        vʸ * (-2R¹ * Rʸˣ + 2Rᵗˣ * Rᵗʸ - 2Rᵗˣʸᶻ * Rᵗᶻ + 2Rˣᶻ * Rᶻʸ) +
        vᶻ * (2R¹ * Rˣᶻ + 2Rᵗˣ * Rᵗᶻ + 2Rᵗˣʸᶻ * Rᵗʸ + 2Rʸˣ * Rᶻʸ)

    v′ʸ =
        vᵗ * (2R¹ * Rᵗʸ + 2Rᵗˣ * Rʸˣ - 2Rᵗˣʸᶻ * Rˣᶻ - 2Rᵗᶻ * Rᶻʸ) +
        vˣ * (2R¹ * Rʸˣ + 2Rᵗˣ * Rᵗʸ + 2Rᵗˣʸᶻ * Rᵗᶻ + 2Rˣᶻ * Rᶻʸ) +
        vʸ * (R¹^2 - Rᵗˣ^2 + Rᵗˣʸᶻ^2 + Rᵗʸ^2 - Rᵗᶻ^2 - Rʸˣ^2 + Rˣᶻ^2 - Rᶻʸ^2) +
        vᶻ * (-2R¹ * Rᶻʸ - 2Rᵗˣ * Rᵗˣʸᶻ + 2Rᵗʸ * Rᵗᶻ + 2Rʸˣ * Rˣᶻ)

    v′ᶻ =
        vᵗ * (2R¹ * Rᵗᶻ - 2Rᵗˣ * Rˣᶻ - 2Rᵗˣʸᶻ * Rʸˣ + 2Rᵗʸ * Rᶻʸ) +
        vˣ * (-2R¹ * Rˣᶻ + 2Rᵗˣ * Rᵗᶻ - 2Rᵗˣʸᶻ * Rᵗʸ + 2Rʸˣ * Rᶻʸ) +
        vʸ * (2R¹ * Rᶻʸ + 2Rᵗˣ * Rᵗˣʸᶻ + 2Rᵗʸ * Rᵗᶻ + 2Rʸˣ * Rˣᶻ) +
        vᶻ * (R¹^2 - Rᵗˣ^2 + Rᵗˣʸᶻ^2 - Rᵗʸ^2 + Rᵗᶻ^2 + Rʸˣ^2 - Rˣᶻ^2 - Rᶻʸ^2)

    vout = similar(v, T)
    vout[1] = v′ᵗ
    vout[2] = v′ˣ
    vout[3] = v′ʸ
    vout[4] = v′ᶻ
    return vout
end
