@doc raw"""
    Lorentz{T<:Real}

A proper orthochronous Lorentz transformation, an element of Spin⁺(3,1) — the double cover
of the restricted Lorentz group SO⁺(3,1).

We work in the spacetime algebra ``Cl(3,1)`` with metric signature ``{−}{+}{+}{+}`` and
basis vectors `𝐭, 𝐱, 𝐲, 𝐳` satisfying `𝐭² = −1`, `𝐱² = 𝐲² = 𝐳² = +1`, all mutually
anticommuting.  The pseudoscalar ``𝐈 = 𝐭𝐱𝐲𝐳`` satisfies ``𝐈² = −𝟏``.

Elements of ``𝐑 ∈ \mathrm{Spin}⁺(3,1)`` live in the even subalgebra (grades 0, 2, 4) and
satisfy ``𝐑 𝐑̃ = 𝟏``, where ``𝐑̃`` is the GA reverse.  In particular, note that that
product *could* include a term proportional to the pseudoscalar; it is zero: ``𝐑 𝐑̃ = 𝟏 +
0 𝐈``.  This subalgebra splits into two parts:

- **Rotation subgroup**: generated by the spatial bivectors `𝐲𝐳`, `𝐱𝐳`, `𝐱𝐲`.
- **Boost sector**: generated by the timelike bivectors `𝐭𝐱`, `𝐭𝐲`, `𝐭𝐳`.

All elements of this algebra commute with the pseudoscalar ``𝐈``, which acts as the complex
unit for this subalgebra.  Note that ``i𝐢 = 𝐭𝐱``, ``i𝐣 = 𝐭𝐲``, ``i𝐤 = 𝐭𝐳``,
relating spatial-rotation generators to boost generators (all with positive signs).
A boost along ``\hat{𝐧} = n^x\,𝐢 + n^y\,𝐣 + n^z\,𝐤`` (a unit `QuatVec`) with
rapidity ``η`` is thus

```math
𝐑 = \cosh(η/2)·𝟏 + \sinh(η/2)·(nˣ 𝐭𝐱 + nʸ 𝐭𝐲 + nᶻ 𝐭𝐳)
```

The two elements ``±R ∈ \mathrm{Spin}⁺(3,1)`` represent the same Lorentz transformation.
The real GA components and their encoding are described in [`ga_components`](@ref); as
usual, you can get the plain (complex) coefficients with [`components`](@ref).

## Operations

Compose with `*`, invert with `inv`, obtain the identity with `one`.
Apply to a Minkowski 4-vector `v = [vᵗ, vˣ, vʸ, vᶻ]` by calling `Λ(v)`.
Access the GA components via [`ga_components`](@ref).

## Constructors

Use the named constructor [`Boost`](@ref).  For a pure rotation, use `Lorentz(R)`.
"""
const Lorentz{T<:Real} = Rotor{Complex{T}}

Lorentz(q::AbstractQuaternion) = Rotor(complex.(components(q))...)
Lorentz(w) = Rotor(complex(w))
Lorentz(w, x, y, z) = Rotor(complex(w), complex(x), complex(y), complex(z))

@doc raw"""
    ga_components(Λ::Lorentz{T}) → SVector{8, T}

Return the eight real geometric-algebra components of `Λ` in Cl(3,1), ordered
as in the even-subalgebra expansion of a Spin⁺(3,1) rotor:

```math
𝐑 = R^1 + R^𝐢\,𝐢 + R^𝐣\,𝐣 + R^𝐤\,𝐤 + R^{𝐭𝐱}\,𝐭𝐱 + R^{𝐭𝐲}\,𝐭𝐲 + R^{𝐭𝐳}\,𝐭𝐳 + R^𝐈\,𝐈
```

where ``𝐈 = 𝐭𝐱𝐲𝐳`` is the pseudoscalar of ``\mathrm{Cl}(3,1)``.

## Storage mapping

`Lorentz{T}` stores a unit quaternion ``𝐑 = w𝟏 + x𝐢 + y𝐣 + z𝐤`` with complex
coefficients ``w, x, y, z ∈ ℂ``, where the quaternionic basis elements `𝐢, 𝐣, 𝐤`
correspond to spatial bivectors according to
```math
\begin{gather}
𝐢 = 𝐳𝐲 = -𝐲𝐳, \\
𝐣 = 𝐱𝐳 = -𝐳𝐱, \\
𝐤 = 𝐲𝐱 = -𝐱𝐲,
\end{gather}
```
and the complex unit ``i ∈ ℂ`` maps to the pseudoscalar ``𝐈 = 𝐭𝐱𝐲𝐳``, so that
```math
\begin{gather}
i𝐢 = 𝐭𝐱𝐲𝐳𝐳𝐲 = 𝐭𝐱, \\
i𝐣 = 𝐭𝐱𝐲𝐳𝐱𝐳 = 𝐭𝐲, \\
i𝐤 = 𝐭𝐱𝐲𝐳𝐲𝐱 = 𝐭𝐳,
\end{gather}
```

The eight real GA components read off from `w, x, y, z` as:

| GA component | quaternion expression | Cl(3,1) basis |
| :----------- | :-------------------- | :------------ |
| `R¹`         | ``\Re(w)``            | ``𝟏``         |
| `Rᶻʸ`        | ``\Re(x)``            | ``𝐳𝐲 = 𝐢``    |
| `Rˣᶻ`        | ``\Re(y)``            | ``𝐱𝐳 = 𝐣``    |
| `Rʸˣ`        | ``\Re(z)``            | ``𝐲𝐱 = 𝐤``    |
| `Rᵗˣ`        | ``\Im(x)``            | ``𝐭𝐱``        |
| `Rᵗʸ`        | ``\Im(y)``            | ``𝐭𝐲``        |
| `Rᵗᶻ`        | ``\Im(z)``            | ``𝐭𝐳``        |
| `Rᵗˣʸᶻ`      | ``\Im(w)``            | ``𝐭𝐱𝐲𝐳``      |

The unit-norm condition ``𝐑𝐑̃ = 𝟏`` — i.e., ``w² + x² + y² + z² = 1`` with complex
arithmetic — translates to two real conditions on the GA components:

```math
\begin{gather}
(R¹)² + (Rᶻʸ)² + (Rˣᶻ)² + (Rʸˣ)² - (Rᵗˣ)² - (Rᵗʸ)² - (Rᵗᶻ)² - (Rᵗˣʸᶻ)² = 1, \\
R¹ Rᵗˣʸᶻ + Rᶻʸ Rᵗˣ + Rˣᶻ Rᵗʸ + Rʸˣ Rᵗᶻ = 0.
\end{gather}
```
"""
function ga_components(Λ::Lorentz{T}) where {T<:Real}
    w, x, y, z = getfield(Λ, :components)
    @SVector [real(w), real(x), real(y), real(z), imag(x), imag(y), imag(z), imag(w)]
end

# ---------------------------------------------------------------------------
# Named constructors
# ---------------------------------------------------------------------------
"""
    Boost(η::T, n̂::AbstractVector) → Lorentz{T}
    Boost(η::T, n̂::QuatVec) → Lorentz{T}

Construct the pure boost with rapidity `η` along the unit direction `n̂`.

The second argument may be either a 3-element `AbstractVector` `[nˣ, nʸ, nᶻ]` or a
`QuatVec` (whose `x`, `y`, `z` components are used as the direction).

In the even subalgebra of Cl(3,1) the rotor is

```math
𝐑 = \\cosh(η/2)·𝟏 + \\sinh(η/2)·(nˣ\\,𝐭𝐱 + nʸ\\,𝐭𝐲 + nᶻ\\,𝐭𝐳).
```

See [`ga_components(::Lorentz)`](@ref) for the correspondence between
this GA form and the quaternion storage.
"""
function Boost(η::T, n̂::AbstractVector) where {T<:Real}
    length(n̂) == 3 || throw(DimensionMismatch(
        "boost direction must be a 3-vector; got length $(length(n̂))"
    ))
    Base.require_one_based_indexing(n̂)
    ch, sh = cosh(η / 2), sinh(η / 2)
    return Rotor{Complex{T}}(
        complex(ch),
        complex(zero(T), sh * n̂[1]),
        complex(zero(T), sh * n̂[2]),
        complex(zero(T), sh * n̂[3]),
    )
end

function Boost(η::T, n̂::QuatVec) where {T<:Real}
    ch, sh = cosh(η / 2), sinh(η / 2)
    _, nx, ny, nz = components(n̂)
    return Rotor{Complex{T}}(
        complex(ch),
        complex(zero(T), sh * nx),
        complex(zero(T), sh * ny),
        complex(zero(T), sh * nz),
    )
end

# ---------------------------------------------------------------------------
# Action on Minkowski 4-vectors
# ---------------------------------------------------------------------------

"""
    (Λ::Lorentz)(v::AbstractVector) → similar(v)

Apply `Λ` to the Minkowski 4-vector `v = [vᵗ, vˣ, vʸ, vᶻ]` (signature −+++)
and return the transformed vector in a fresh container of the same type with
element type `T`.

The action is the Spin⁺(3,1) sandwich `V′ = R·V·R̃` in Cl(3,1), where `R̃` is
the GA reverse.  The eight real GA components `(R¹, Rᶻʸ, …, Rᵗˣʸᶻ)` are
extracted via [`ga_components(::Lorentz)`](@ref), and the bilinear
expansion of the grade-1 projection of `R·V·R̃` is applied directly.
"""
function (Λ::Lorentz)(v::AbstractVector)
    return typeof(v)(Λ(SVector{4}(v)))
end
function (Λ::Lorentz{T1})(v::SVector{4, T2}) where {T1<:Real, T2<:Real}
    R¹, Rᶻʸ, Rˣᶻ, Rʸˣ, Rᵗˣ, Rᵗʸ, Rᵗᶻ, Rᵗˣʸᶻ = ga_components(Λ)

    v′ᵗ = v ⋅ @SVector [
        R¹^2 + Rᵗˣ^2 + Rᵗˣʸᶻ^2 + Rᵗʸ^2 + Rᵗᶻ^2 + Rʸˣ^2 + Rˣᶻ^2 + Rᶻʸ^2,
        2R¹ * Rᵗˣ - 2Rᵗˣʸᶻ * Rᶻʸ + 2Rᵗʸ * Rʸˣ - 2Rᵗᶻ * Rˣᶻ,
        2R¹ * Rᵗʸ - 2Rᵗˣ * Rʸˣ - 2Rᵗˣʸᶻ * Rˣᶻ + 2Rᵗᶻ * Rᶻʸ,
        2R¹ * Rᵗᶻ + 2Rᵗˣ * Rˣᶻ - 2Rᵗˣʸᶻ * Rʸˣ - 2Rᵗʸ * Rᶻʸ
    ]

    v′ˣ = v ⋅ @SVector [
        2R¹ * Rᵗˣ - 2Rᵗˣʸᶻ * Rᶻʸ - 2Rᵗʸ * Rʸˣ + 2Rᵗᶻ * Rˣᶻ,
        R¹^2 + Rᵗˣ^2 + Rᵗˣʸᶻ^2 - Rᵗʸ^2 - Rᵗᶻ^2 - Rʸˣ^2 - Rˣᶻ^2 + Rᶻʸ^2,
        -2R¹ * Rʸˣ + 2Rᵗˣ * Rᵗʸ - 2Rᵗˣʸᶻ * Rᵗᶻ + 2Rˣᶻ * Rᶻʸ,
        2R¹ * Rˣᶻ + 2Rᵗˣ * Rᵗᶻ + 2Rᵗˣʸᶻ * Rᵗʸ + 2Rʸˣ * Rᶻʸ
    ]

    v′ʸ = v ⋅ @SVector [
        2R¹ * Rᵗʸ + 2Rᵗˣ * Rʸˣ - 2Rᵗˣʸᶻ * Rˣᶻ - 2Rᵗᶻ * Rᶻʸ,
        2R¹ * Rʸˣ + 2Rᵗˣ * Rᵗʸ + 2Rᵗˣʸᶻ * Rᵗᶻ + 2Rˣᶻ * Rᶻʸ,
        R¹^2 - Rᵗˣ^2 + Rᵗˣʸᶻ^2 + Rᵗʸ^2 - Rᵗᶻ^2 - Rʸˣ^2 + Rˣᶻ^2 - Rᶻʸ^2,
        -2R¹ * Rᶻʸ - 2Rᵗˣ * Rᵗˣʸᶻ + 2Rᵗʸ * Rᵗᶻ + 2Rʸˣ * Rˣᶻ
    ]

    v′ᶻ = v ⋅ @SVector [
        2R¹ * Rᵗᶻ - 2Rᵗˣ * Rˣᶻ - 2Rᵗˣʸᶻ * Rʸˣ + 2Rᵗʸ * Rᶻʸ,
        -2R¹ * Rˣᶻ + 2Rᵗˣ * Rᵗᶻ - 2Rᵗˣʸᶻ * Rᵗʸ + 2Rʸˣ * Rᶻʸ,
        2R¹ * Rᶻʸ + 2Rᵗˣ * Rᵗˣʸᶻ + 2Rᵗʸ * Rᵗᶻ + 2Rʸˣ * Rˣᶻ,
        R¹^2 - Rᵗˣ^2 + Rᵗˣʸᶻ^2 - Rᵗʸ^2 + Rᵗᶻ^2 + Rʸˣ^2 - Rˣᶻ^2 - Rᶻʸ^2
    ]
    
    v′ = @SVector [v′ᵗ, v′ˣ, v′ʸ, v′ᶻ]

    return v′
end

# -------------------------------------------------
# ℂ-conjugation: component-wise complex operations,
# as distinct from conjugate by the GA reverse
# -------------------------------------------------

"""
    ℂconj(Λ::Lorentz{T}) → Lorentz{T}

Component-wise complex conjugate of `Λ`: conjugate each complex coefficient `(w, x, y, z) →
(w̄, x̄, ȳ, z̄)`.

This is distinct from the GA reverse, which is `conj(Λ)` and just negates the quaternion
"vector" part.  For `Λ = R*B` with `R` a pure rotation and `B` a pure boost, `ℂconj(Λ) = R *
B⁻¹`, since `ℂconj(B) = B⁻¹` for pure boosts and `ℂconj(R) = R` for real rotors.
"""
ℂconj(Λ::Lorentz{T}) where {T<:Real} = Rotor{Complex{T}}(
    conj(Λ[1]), conj(Λ[2]), conj(Λ[3]), conj(Λ[4])
)

"""
    ℂreal(Λ::Lorentz{T}) → Quaternion{T}

Complex-real part of `Λ`: `Quaternion(real(Λ[1]), real(Λ[2]), real(Λ[3]), real(Λ[4]))`.

For `Λ = R*B` where `R` is a pure rotation and `B` is a pure boost with rapidity `η`, this
equals `cosh(η/2)*R`.  Its Euclidean norm is `cosh(η/2) ≥ 1`.

This is distinct from the GA "real" part, given by `real(Λ)`, which is constructed from the
reverse, rather than the complex-conjugate.  That will just be the scalar part of `Λ`, but
may be complex; this function returns a full quaternion, with all components real.
"""
ℂreal(Λ::Lorentz{T}) where {T<:Real} = Quaternion{T}(
    real(Λ[1]), real(Λ[2]), real(Λ[3]), real(Λ[4])
)

"""
    ℂimag(Λ::Lorentz{T}) → Quaternion{T}

Imaginary-part of `Λ`: `Quaternion(imag(Λ[1]), imag(Λ[2]), imag(Λ[3]), imag(Λ[4]))`.

For `Λ = R*B` where `R` is a pure rotation and `B` is a pure boost with rapidity `η` in
direction `n̂`, this equals `sinh(η/2)*R*n̂`.

This is distinct from the GA "imaginary" part, given by `imag(Λ)`, which is constructed from
the reverse, rather than the complex-conjugate.  That will just be the quaternion "vector"
part of `Λ`, but may be complex; this function returns a full quaternion, with all
components real.
"""
ℂimag(Λ::Lorentz{T}) where {T<:Real} = Quaternion{T}(
    imag(Λ[1]), imag(Λ[2]), imag(Λ[3]), imag(Λ[4])
)

"""
    ℂreim(Λ::Lorentz{T}) → (Quaternion{T}, Quaternion{T})

Return `(ℂreal(Λ), ℂimag(Λ))` as a single call.
"""
ℂreim(Λ::Lorentz{T}) where {T<:Real} = (ℂreal(Λ), ℂimag(Λ))

# ---------------------------------------------------------------------------
# Polar decomposition
# ---------------------------------------------------------------------------

"""
    RB(Λ::Lorentz{T}) → (R::Rotor{T}, B::Lorentz{T})

Polar decomposition `Λ = R * B`: pure rotation `R` followed by pure boost `B`.

!!! note "Double cover"
    Since `Spin⁺(3,1)` is a double cover of `SO⁺(3,1)`, both `(R, B)` and `(-R, -B)`
    represent the same Lorentz transformation.  The scalar part of the returned `R` has the
    same sign as the scalar part of `Λ`.

The general Lorentz transformation `Λ` can be expressed as the product of a pure rotation
`R` and a pure boost `B` in either order.  For this function, we assume `Λ = R * B`.  The
boost is, in turn, determined by a rapidity `η ≥ 0` and a unit direction `n̂`, so that
`B = cosh(η/2) + im*sinh(η/2)*n̂` in the quaternionic encoding.  Therefore, we have

    Λ = R * B = cosh(η/2)*R + im*sinh(η/2)*(R*n̂).

Since `cosh(η/2)` is 1 for no boost, and grows smoothly with `η`, we can find `R` very
simply by normalizing the complex-real part of `Λ`.  And since the norm of `R` is 1, we can
find `cosh(η/2)` as the magnitude of the complex-real part of `Λ`.  Then, we find
`sinh(η/2)*n̂` simply by multiplying the complex-imaginary part of `Λ` by `inv(R)`, and
reconstruct `B` simply by adding the result to `cosh(η/2)`.

See also [`BR`](@ref).
"""
function RB(Λ::Lorentz{T}) where {T<:Real}
    ℜΛ, ℑΛ = ℂreim(Λ)
    R = rotor(ℜΛ)
    B = Lorentz(abs(ℜΛ) + im * (conj(R) * ℑΛ))
    return R, B
end

"""
    BR(Λ::Lorentz{T}) → (B::Lorentz{T}, R::Rotor{T})

Polar decomposition `Λ = B * R`: pure boost `B` followed by pure rotation `R`.

The algorithm here is the same as for [`RB`](@ref), but with the order of multiplication by
`inv(R)` reversed.
"""
function BR(Λ::Lorentz{T}) where {T<:Real}
    ℜΛ, ℑΛ = ℂreim(Λ)
    R = rotor(ℜΛ)
    B = Lorentz(abs(ℜΛ) + im * (ℑΛ * conj(R)))
    return B, R
end
